version: "3.7"

services:
  web:
    image: maks3w/aws-lambda-rie-gateway:latest
    environment:
      TARGET_URL: http://application:8080
    ports:
      - target: 8080
        published: 8080
        protocol: tcp

  application:
    build:
      context: ./
      target: development
